#!/usr/bin/env ruby

require 'gelf'

logger = GELF::Notifier.new("localhost", 12201)

rnd = Random.new.rand(0..999)
logger.notify!(:short_message => "foo" + rnd.to_s, :full_message => "Bla Test from cronjob, every minute")
